
POST https://practicum-elect.herokuapp.com/api/model2/predict
=======


{"Id": "0", "Open Date": "01/22/2011", "City": "Niğde", "City Group": "Other", "Type": "FC", "P1": "1", "P2": "4.0", "P3": "4.0", "P4": "4.0", "P5": "1", "P6": "2", "P7": "5", "P8": "4", "P9": "5", "P10": "5", "P11": "5", "P12": "3", "P13": "4.0", "P14": "0", "P15": "0", "P16": "0", "P17": "2", "P18": "0", "P19": "5", "P20": "5", "P21": "3", "P22": "1", "P23": "4", "P24": "0", "P25": "0", "P26": "0.0", "P27": "0.0", "P28": "2.0", "P29": "3.0", "P30": "0", "P31": "0", "P32": "0", "P33": "0", "P34": "0", "P35": "0", "P36": "0", "P37": "0"}